export let theApi = [
  {
    id: 1,
    image: "img/phone1.png",
    title: "iPad 10th Generation",
    category: "mobile",
    price: 280.0,
    review: 4,
    inStock: 52,
  },
  {
    id: 2,
    image: "img/phone2.png",
    title: "Galaxy Note20 Ultra 5G",
    category: "mobile",
    price: 420.0,
    review: 3,
    inStock: 58,
  },
  {
    id: 3,
    image: "img/phone3.png",
    title: "Sony Xperia 1 III Dual-SIM",
    category: "mobile",
    price: 250.0,
    review: 4,
    inStock: 60,
  },
  {
    id: 4,
    image: "img/phone4.png",
    title: "iPhone 15 Pro Max",
    category: "mobile",
    price: 480.0,
    review: 4.5,
    inStock: 36,
  },
  {
    id: 5,
    image: "img/phone5.png",
    title: "Samsung Galaxy Note 20",
    category: "mobile",
    price: 265.0,
    review: 3.5,
    inStock: 42,
  },
];
